[versions]
# -- Build Plugins (Mengambil versi terbaru/HEAD) --
agp = "8.6.0"
kotlin = "1.9.24"
googleGmsGoogleServices = "4.4.2"

# -- Android Core --
coreKtx = "1.13.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.1.4"

# -- Firebase BOM (Mengatur semua versi Firebase) --
firebaseBom = "32.7.0"

# -- Database Lokal & Gambar --
room = "2.6.1"
glide = "4.16.0"

# -- Testing --
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
activityVersion = "1.12.2"
firebaseStorageKtx = "22.0.1"

[libraries]
# -- Android Core --
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# -- Firebase (Menggunakan BOM) --
# Dengan BOM, library di bawahnya TIDAK butuh "version.ref"
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
# Saya tetap simpan database (Realtime DB) jaga-jaga jika ada kode lama yang belum dihapus
firebase-database = { group = "com.google.firebase", name = "firebase-database" }

# -- Room Database --
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# -- Glide (Gambar) --
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }

# -- Testing --
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activityVersion" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebaseStorageKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }